// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package protomsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgBodyTag int32

const (
	MsgBodyTag_AddMony     MsgBodyTag = 0
	MsgBodyTag_AddMonyRsp  MsgBodyTag = 1
	MsgBodyTag_RegisterReq MsgBodyTag = 2
)

var MsgBodyTag_name = map[int32]string{
	0: "AddMony",
	1: "AddMonyRsp",
	2: "RegisterReq",
}

var MsgBodyTag_value = map[string]int32{
	"AddMony":     0,
	"AddMonyRsp":  1,
	"RegisterReq": 2,
}

func (x MsgBodyTag) String() string {
	return proto.EnumName(MsgBodyTag_name, int32(x))
}

func (MsgBodyTag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type RpcMessage struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	NodeID               string   `protobuf:"bytes,3,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Params               []*Param `protobuf:"bytes,4,rep,name=Params,proto3" json:"Params,omitempty"`
	Timeout              int64    `protobuf:"varint,5,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Result               string   `protobuf:"bytes,6,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string   `protobuf:"bytes,7,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcMessage) Reset()         { *m = RpcMessage{} }
func (m *RpcMessage) String() string { return proto.CompactTextString(m) }
func (*RpcMessage) ProtoMessage()    {}
func (*RpcMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *RpcMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcMessage.Unmarshal(m, b)
}
func (m *RpcMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcMessage.Marshal(b, m, deterministic)
}
func (m *RpcMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcMessage.Merge(m, src)
}
func (m *RpcMessage) XXX_Size() int {
	return xxx_messageInfo_RpcMessage.Size(m)
}
func (m *RpcMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RpcMessage proto.InternalMessageInfo

func (m *RpcMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RpcMessage) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RpcMessage) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *RpcMessage) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *RpcMessage) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RpcMessage) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *RpcMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Param struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Param) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RpcMessageReq struct {
	Msg                  *RpcMessage `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RpcMessageReq) Reset()         { *m = RpcMessageReq{} }
func (m *RpcMessageReq) String() string { return proto.CompactTextString(m) }
func (*RpcMessageReq) ProtoMessage()    {}
func (*RpcMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *RpcMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcMessageReq.Unmarshal(m, b)
}
func (m *RpcMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcMessageReq.Marshal(b, m, deterministic)
}
func (m *RpcMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcMessageReq.Merge(m, src)
}
func (m *RpcMessageReq) XXX_Size() int {
	return xxx_messageInfo_RpcMessageReq.Size(m)
}
func (m *RpcMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_RpcMessageReq proto.InternalMessageInfo

func (m *RpcMessageReq) GetMsg() *RpcMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type RpcMessageRsp struct {
	Msg                  *RpcMessage `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RpcMessageRsp) Reset()         { *m = RpcMessageRsp{} }
func (m *RpcMessageRsp) String() string { return proto.CompactTextString(m) }
func (*RpcMessageRsp) ProtoMessage()    {}
func (*RpcMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *RpcMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcMessageRsp.Unmarshal(m, b)
}
func (m *RpcMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcMessageRsp.Marshal(b, m, deterministic)
}
func (m *RpcMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcMessageRsp.Merge(m, src)
}
func (m *RpcMessageRsp) XXX_Size() int {
	return xxx_messageInfo_RpcMessageRsp.Size(m)
}
func (m *RpcMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RpcMessageRsp proto.InternalMessageInfo

func (m *RpcMessageRsp) GetMsg() *RpcMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type RpcRequestMsg struct {
	Msgtype              MsgBodyTag `protobuf:"varint,1,opt,name=Msgtype,proto3,enum=protomsg.MsgBodyTag" json:"Msgtype,omitempty"`
	Data                 string     `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RpcRequestMsg) Reset()         { *m = RpcRequestMsg{} }
func (m *RpcRequestMsg) String() string { return proto.CompactTextString(m) }
func (*RpcRequestMsg) ProtoMessage()    {}
func (*RpcRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *RpcRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcRequestMsg.Unmarshal(m, b)
}
func (m *RpcRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcRequestMsg.Marshal(b, m, deterministic)
}
func (m *RpcRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcRequestMsg.Merge(m, src)
}
func (m *RpcRequestMsg) XXX_Size() int {
	return xxx_messageInfo_RpcRequestMsg.Size(m)
}
func (m *RpcRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RpcRequestMsg proto.InternalMessageInfo

func (m *RpcRequestMsg) GetMsgtype() MsgBodyTag {
	if m != nil {
		return m.Msgtype
	}
	return MsgBodyTag_AddMony
}

func (m *RpcRequestMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RpcResponseMsg struct {
	Msgtype              string   `protobuf:"bytes,1,opt,name=Msgtype,proto3" json:"Msgtype,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcResponseMsg) Reset()         { *m = RpcResponseMsg{} }
func (m *RpcResponseMsg) String() string { return proto.CompactTextString(m) }
func (*RpcResponseMsg) ProtoMessage()    {}
func (*RpcResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *RpcResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcResponseMsg.Unmarshal(m, b)
}
func (m *RpcResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcResponseMsg.Marshal(b, m, deterministic)
}
func (m *RpcResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcResponseMsg.Merge(m, src)
}
func (m *RpcResponseMsg) XXX_Size() int {
	return xxx_messageInfo_RpcResponseMsg.Size(m)
}
func (m *RpcResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RpcResponseMsg proto.InternalMessageInfo

func (m *RpcResponseMsg) GetMsgtype() string {
	if m != nil {
		return m.Msgtype
	}
	return ""
}

func (m *RpcResponseMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *RpcResponseMsg) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//加钱的消息
type AddMonyBody struct {
	Amount               int32    `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMonyBody) Reset()         { *m = AddMonyBody{} }
func (m *AddMonyBody) String() string { return proto.CompactTextString(m) }
func (*AddMonyBody) ProtoMessage()    {}
func (*AddMonyBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *AddMonyBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMonyBody.Unmarshal(m, b)
}
func (m *AddMonyBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMonyBody.Marshal(b, m, deterministic)
}
func (m *AddMonyBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMonyBody.Merge(m, src)
}
func (m *AddMonyBody) XXX_Size() int {
	return xxx_messageInfo_AddMonyBody.Size(m)
}
func (m *AddMonyBody) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMonyBody.DiscardUnknown(m)
}

var xxx_messageInfo_AddMonyBody proto.InternalMessageInfo

func (m *AddMonyBody) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

//加钱的消息
type AddMonyBodyRsp struct {
	Amount               int32    `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	RespMsg              string   `protobuf:"bytes,2,opt,name=RespMsg,proto3" json:"RespMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMonyBodyRsp) Reset()         { *m = AddMonyBodyRsp{} }
func (m *AddMonyBodyRsp) String() string { return proto.CompactTextString(m) }
func (*AddMonyBodyRsp) ProtoMessage()    {}
func (*AddMonyBodyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *AddMonyBodyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMonyBodyRsp.Unmarshal(m, b)
}
func (m *AddMonyBodyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMonyBodyRsp.Marshal(b, m, deterministic)
}
func (m *AddMonyBodyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMonyBodyRsp.Merge(m, src)
}
func (m *AddMonyBodyRsp) XXX_Size() int {
	return xxx_messageInfo_AddMonyBodyRsp.Size(m)
}
func (m *AddMonyBodyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMonyBodyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddMonyBodyRsp proto.InternalMessageInfo

func (m *AddMonyBodyRsp) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AddMonyBodyRsp) GetRespMsg() string {
	if m != nil {
		return m.RespMsg
	}
	return ""
}

type RegisterBodyReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassWd               string   `protobuf:"bytes,2,opt,name=PassWd,proto3" json:"PassWd,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterBodyReq) Reset()         { *m = RegisterBodyReq{} }
func (m *RegisterBodyReq) String() string { return proto.CompactTextString(m) }
func (*RegisterBodyReq) ProtoMessage()    {}
func (*RegisterBodyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *RegisterBodyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterBodyReq.Unmarshal(m, b)
}
func (m *RegisterBodyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterBodyReq.Marshal(b, m, deterministic)
}
func (m *RegisterBodyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterBodyReq.Merge(m, src)
}
func (m *RegisterBodyReq) XXX_Size() int {
	return xxx_messageInfo_RegisterBodyReq.Size(m)
}
func (m *RegisterBodyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterBodyReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterBodyReq proto.InternalMessageInfo

func (m *RegisterBodyReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterBodyReq) GetPassWd() string {
	if m != nil {
		return m.PassWd
	}
	return ""
}

func (m *RegisterBodyReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type RegisterBodyRsp struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterBodyRsp) Reset()         { *m = RegisterBodyRsp{} }
func (m *RegisterBodyRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterBodyRsp) ProtoMessage()    {}
func (*RegisterBodyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *RegisterBodyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterBodyRsp.Unmarshal(m, b)
}
func (m *RegisterBodyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterBodyRsp.Marshal(b, m, deterministic)
}
func (m *RegisterBodyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterBodyRsp.Merge(m, src)
}
func (m *RegisterBodyRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterBodyRsp.Size(m)
}
func (m *RegisterBodyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterBodyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterBodyRsp proto.InternalMessageInfo

func (m *RegisterBodyRsp) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RegisterBodyRsp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterBodyRsp) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func init() {
	proto.RegisterEnum("protomsg.MsgBodyTag", MsgBodyTag_name, MsgBodyTag_value)
	proto.RegisterType((*RpcMessage)(nil), "protomsg.RpcMessage")
	proto.RegisterType((*Param)(nil), "protomsg.Param")
	proto.RegisterType((*RpcMessageReq)(nil), "protomsg.RpcMessageReq")
	proto.RegisterType((*RpcMessageRsp)(nil), "protomsg.RpcMessageRsp")
	proto.RegisterType((*RpcRequestMsg)(nil), "protomsg.RpcRequestMsg")
	proto.RegisterType((*RpcResponseMsg)(nil), "protomsg.RpcResponseMsg")
	proto.RegisterType((*AddMonyBody)(nil), "protomsg.AddMonyBody")
	proto.RegisterType((*AddMonyBodyRsp)(nil), "protomsg.AddMonyBodyRsp")
	proto.RegisterType((*RegisterBodyReq)(nil), "protomsg.RegisterBodyReq")
	proto.RegisterType((*RegisterBodyRsp)(nil), "protomsg.RegisterBodyRsp")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0x37, 0xc9, 0xb6, 0xdd, 0xbe, 0x60, 0x5a, 0x86, 0x45, 0x06, 0x4f, 0x25, 0xa0, 0x16, 0x0f,
	0x15, 0xd6, 0x83, 0xe0, 0x6d, 0x97, 0x7a, 0x28, 0x92, 0xb2, 0x8c, 0x55, 0xf1, 0x38, 0x6e, 0x1e,
	0x63, 0x71, 0xd3, 0x49, 0xf3, 0x26, 0x87, 0x7e, 0x38, 0xbf, 0x9b, 0xcc, 0x9f, 0xb4, 0xb1, 0xe2,
	0xe2, 0x29, 0xf3, 0x7b, 0x79, 0xbf, 0x3f, 0xef, 0xcd, 0xc0, 0xb8, 0x22, 0xb5, 0xa8, 0x1b, 0x6d,
	0x34, 0xbb, 0x74, 0x9f, 0x8a, 0x54, 0xfe, 0x2b, 0x02, 0x10, 0xf5, 0x7d, 0x81, 0x44, 0x52, 0x21,
	0xcb, 0x20, 0x5e, 0x2d, 0x79, 0x34, 0x8b, 0xe6, 0x63, 0x11, 0xaf, 0x96, 0xec, 0x19, 0x0c, 0x0b,
	0x34, 0x3f, 0x74, 0xc9, 0x63, 0x57, 0x0b, 0xc8, 0xd6, 0xd7, 0xba, 0xc4, 0xd5, 0x92, 0x27, 0xbe,
	0xee, 0x11, 0x7b, 0x05, 0xc3, 0x3b, 0xd9, 0xc8, 0x8a, 0xf8, 0xc5, 0x2c, 0x99, 0xa7, 0xd7, 0x93,
	0x45, 0xe7, 0xb4, 0x70, 0x75, 0x11, 0x7e, 0x33, 0x0e, 0xa3, 0xcd, 0xb6, 0x42, 0xdd, 0x1a, 0x3e,
	0x98, 0x45, 0xf3, 0x44, 0x74, 0xd0, 0x4a, 0x0b, 0xa4, 0xf6, 0xc1, 0xf0, 0xa1, 0x97, 0xf6, 0x88,
	0x5d, 0xc1, 0xe0, 0x43, 0xd3, 0xe8, 0x86, 0x8f, 0x5c, 0xd9, 0x83, 0xfc, 0x0d, 0x0c, 0x9c, 0x22,
	0x9b, 0x42, 0xf2, 0x11, 0x0f, 0x21, 0xba, 0x3d, 0x5a, 0xc2, 0x17, 0xf9, 0xd0, 0x62, 0x88, 0xee,
	0x41, 0xfe, 0x0e, 0x9e, 0x9e, 0xe6, 0x15, 0xb8, 0x67, 0x2f, 0x21, 0x29, 0x48, 0x39, 0x62, 0x7a,
	0x7d, 0x75, 0xca, 0xdb, 0xeb, 0xb2, 0x0d, 0x67, 0x44, 0xaa, 0xff, 0x9b, 0xf8, 0xc9, 0x11, 0x05,
	0xee, 0x5b, 0x24, 0x53, 0x90, 0x62, 0x0b, 0x18, 0x15, 0xa4, 0xcc, 0xa1, 0x46, 0x47, 0xce, 0xfa,
	0xe4, 0x82, 0xd4, 0xad, 0x2e, 0x0f, 0x1b, 0xa9, 0x44, 0xd7, 0xc4, 0x18, 0x5c, 0x2c, 0xa5, 0x91,
	0x61, 0x0e, 0x77, 0xce, 0x37, 0x90, 0x39, 0x51, 0xaa, 0xf5, 0x8e, 0xd0, 0xaa, 0xf2, 0x3f, 0x55,
	0xc7, 0x8f, 0xf2, 0x4f, 0xdb, 0x4c, 0xfa, 0xdb, 0x7c, 0x01, 0xe9, 0x4d, 0x59, 0x16, 0x7a, 0x77,
	0xb0, 0x21, 0xec, 0x55, 0xdc, 0x54, 0xba, 0xdd, 0x19, 0xa7, 0x38, 0x10, 0x01, 0xe5, 0xb7, 0x90,
	0xf5, 0xda, 0xec, 0x2e, 0xfe, 0xd1, 0x69, 0x43, 0xd9, 0x8c, 0x76, 0x4f, 0xde, 0xbd, 0x83, 0xb9,
	0x84, 0x89, 0x40, 0xb5, 0x25, 0x83, 0x8d, 0x13, 0xc1, 0x3d, 0x7b, 0x0e, 0x97, 0x9f, 0x09, 0x9b,
	0xb5, 0xac, 0xba, 0x11, 0x8e, 0xd8, 0x1a, 0xdc, 0x49, 0xa2, 0xaf, 0xc7, 0x87, 0xe8, 0x91, 0xe5,
	0xac, 0xb7, 0xf7, 0x3f, 0x1d, 0xc7, 0x8f, 0x72, 0xc4, 0xf9, 0xb7, 0x33, 0x0b, 0xaa, 0xff, 0x7a,
	0xdf, 0x7d, 0xcb, 0xf8, 0xcc, 0xf2, 0x11, 0xe9, 0xd7, 0xef, 0x01, 0x4e, 0x37, 0xc5, 0x52, 0x18,
	0x85, 0x7d, 0x4c, 0x9f, 0xb0, 0x0c, 0x20, 0x00, 0x41, 0xf5, 0x34, 0x62, 0x13, 0x48, 0xbb, 0x14,
	0x02, 0xf7, 0xd3, 0xf8, 0xfb, 0xd0, 0x5d, 0xf6, 0xdb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b,
	0x4f, 0x19, 0xf1, 0x90, 0x03, 0x00, 0x00,
}
